// service-worker.js
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

// Precache and route all files generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache API requests
registerRoute(
  ({ url }) => url.origin === 'https://ps-ui-f7ff0.web.app/', // replace with your API URL
  new StaleWhileRevalidate({
    cacheName: 'api-cache',
    plugins: [
      // Any additional plugin options
    ],
  })
);

// Add more caching strategies as needed
